Update documentation for appointment commands
AY2021S2-CS2103T-W10-4/tp pull request #239
Opened 2021-04-04 09:32 UTC by picasdan9

2021-04-04 10:37 UTC, SiTingST requested changes

2021-04-04 10:37 UTC, SiTingST commented on docs/UserGuide.md
> +* Date must be of the format `YYYY-MM-DD`.
Lines 200 to 202 are the same as lines 226 to 228. Perhaps you can write this in the parameter format section to avoid duplication?

2021-04-04 10:49 UTC, picasdan9 commented on docs/UserGuide.md
> +* Date must be of the format `YYYY-MM-DD`.
good idea! will make the amendment.

2021-04-04 11:15 UTC, picasdan9 commented on docs/UserGuide.md
> +* Date must be of the format `YYYY-MM-DD`.
on a second thought, would it be better to repeat the information? the reason is that if a reader navigates directly to a feature, then they will know the relevant conditions for using this command. If we refactor and put this in the parameter format section, the reader might miss it. another alternative is to have an in-page hyperlink that directs to a subsection called "Conditions for valid appointments" (which would also talk about no clash and pre-existence of student etc.)

2021-04-05 10:13 UTC, SiTingST requested changes

2021-04-05 10:13 UTC, SiTingST commented on docs/UserGuide.md
> +* Date must be of the format `YYYY-MM-DD`.
The in-page hyperlink idea sounds good!

2021-04-06 16:06 UTC, SiTingST approved these changes
LGTM!

2021-04-06 16:11 UTC, merged